# Kimlik ve Sunucu Bilgileri
sonar.projectKey=OncoMind
sonar.host.url=http://localhost:9000
sonar.token=sqa_70368b3eb8d6330ba683202a6b75bf68a979e2c8

# Kaynak Klasör
sonar.sources=.

# Analiz Edilmeyecek Dizinler ve Dosya Tipleri (Virgülle ayrılır)
sonar.exclusions=**/node_modules/**, **/bin/**, **/obj/**, **/venv/**, **/.venv/**, **/.ipynb_checkpoints/**, **/Migrations/**, **/*.pt, **/*.pth, **/*.onnx, **/*.csv, **/*.tsv, **/*.json, **/*.h5, **/*.md, **/package-lock.json, **/*.cs, **/*.csproj, **/*.sln

# C# (.NET) projeleri için özel ayarlar (Eğer C# kodunu taramasını istiyorsan)
# Ancak şu an sadece statik analiz yapmak için C# derlemesini atlıyoruz
sonar.cs.roslyn.ignoreIssues=false