name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Restore & Build
        run: |
          dotnet restore OncoMind.Api/OncoMind.Api.csproj
          dotnet build OncoMind.Api/OncoMind.Api.csproj -c Release --no-restore

  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        working-directory: oncomind-ml
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: (optional) Run tests
        working-directory: oncomind-ml
        run: |
          # add tests later; for now list files
          python -c "import sys; print('python ok', sys.version)"

  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install & Build Frontend
        working-directory: oncomind-frontend
        run: |
          npm ci
          npm run build --if-present
